/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.pembayaran;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import main.Koneksi;
import main.cetak.CetakBuktiPembayaran;

/**
 *
 * @author User
 */
public class PembayaranForm extends javax.swing.JInternalFrame {

    String rawat;
    String kodeperiksa;
    
    private void reset(){
        txtkodepembayaran.setEditable(false);
        txtkodeperiksa.setText(null);
        txtnamapasien.setText(null);
        txtnamadokter.setText(null);
        txttindakan.setText(null);
        txttotal.setText(null);
        txtbayar.setText(null);
        txtkembalian.setText(null);
        
        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncaripemeriksaan.setEnabled(true);

        kodeBayar();

    }
    
    private void kodeBayar(){
        try{
            String sql = "SELECT MAX(right(id, 1)) AS id FROM pembayaran";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                int kode = res.getInt(1);
                String AN = "" + (kode + 1);
                String Nol = "";
                
                if(AN.length() == 1){
                    Nol = "00";
                }else if(AN.length() == 2){
                    Nol = "0";
                }else if(AN.length() == 3){
                    Nol = "";
                }
                
                txtkodepembayaran.setText("BYR" + Nol + AN);
                
            } else {
                txtkodepembayaran.setText("BYR001");
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    
    public PembayaranForm() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        kodeBayar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormPembayaran = new javax.swing.JPanel();
        btncari = new javax.swing.JButton();
        btncaripemeriksaan = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtkodepembayaran = new javax.swing.JTextField();
        txtkodeperiksa = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnDataPembayaran = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtnamapasien = new javax.swing.JTextField();
        txtnamadokter = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txttindakan = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        btncetakfaktur = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        panelFormPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        panelFormPembayaran.setMaximumSize(new java.awt.Dimension(900, 900));
        panelFormPembayaran.setPreferredSize(new java.awt.Dimension(780, 480));

        btncari.setBackground(new java.awt.Color(255, 255, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btncari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncari.setBorderPainted(false);
        btncari.setContentAreaFilled(false);
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.setFocusable(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        btncaripemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btncaripemeriksaan.setBorderPainted(false);
        btncaripemeriksaan.setContentAreaFilled(false);
        btncaripemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncaripemeriksaan.setFocusable(false);
        btncaripemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripemeriksaanActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setText("Kode Pembayaran");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 255));
        jLabel28.setText("Kode Periksa");

        txtkodepembayaran.setEditable(false);
        txtkodepembayaran.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtkodepembayaran.setText("Otomatis");
        txtkodepembayaran.setToolTipText("");
        txtkodepembayaran.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        txtkodeperiksa.setEditable(false);
        txtkodeperiksa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtkodeperiksa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        jLabel75.setBackground(new java.awt.Color(102, 102, 255));
        jLabel75.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(51, 51, 255));
        jLabel75.setText("Input Data Pembayaran");

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Vector.png"))); // NOI18N
        btnsimpan.setText(" Simpan");
        btnsimpan.setFocusable(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Vector-1.png"))); // NOI18N
        btnupdate.setText(" Update");
        btnupdate.setEnabled(false);
        btnupdate.setFocusable(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2802.png"))); // NOI18N
        btndelete.setText(" Delete");
        btndelete.setEnabled(false);
        btndelete.setFocusable(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2803.png"))); // NOI18N
        btnreset.setText(" Reset");
        btnreset.setFocusable(false);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnDataPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clipboard-square-symbol.png"))); // NOI18N
        btnDataPembayaran.setText(" Data Pembayaran");
        btnDataPembayaran.setFocusable(false);
        btnDataPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPembayaranActionPerformed(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 255));
        jLabel35.setText("Nama Pasien");

        txtnamapasien.setEditable(false);
        txtnamapasien.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtnamapasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        txtnamadokter.setEditable(false);
        txtnamadokter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtnamadokter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 255));
        jLabel36.setText("Nama Dokter");

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 255));
        jLabel37.setText("Tindakan");

        txttindakan.setEditable(false);
        txttindakan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txttindakan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txttotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 255));
        jLabel38.setText("Total Tagihan");

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 255));
        jLabel39.setText("Pembayaran");

        txtbayar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtbayar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 255));
        jLabel40.setText("Kembalian");

        txtkembalian.setEditable(false);
        txtkembalian.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtkembalian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));

        btncetakfaktur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N
        btncetakfaktur.setText(" Cetak Bukti Pembayaran");
        btncetakfaktur.setFocusable(false);
        btncetakfaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakfakturActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormPembayaranLayout = new javax.swing.GroupLayout(panelFormPembayaran);
        panelFormPembayaran.setLayout(panelFormPembayaranLayout);
        panelFormPembayaranLayout.setHorizontalGroup(
            panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel75))
                    .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnamadokter, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPembayaranLayout.createSequentialGroup()
                                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel28))
                                        .addGap(29, 29, 29))
                                    .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(62, 62, 62)))
                                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtkodeperiksa, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtkodepembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncaripemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDataPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncetakfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelFormPembayaranLayout.setVerticalGroup(
            panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addGap(38, 38, 38)
                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btncetakfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDataPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPembayaranLayout.createSequentialGroup()
                                .addComponent(btncaripemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126))))
                    .addGroup(panelFormPembayaranLayout.createSequentialGroup()
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkodepembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtkodeperiksa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(txtnamadokter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txttindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelFormPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFormPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFormPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        String id = JOptionPane.showInputDialog(null, "Cari Berdasarkan Kode Pembayaran!!!");
        try{
            String sql = "SELECT * FROM pembayaran "
                    + "INNER JOIN pemeriksaan ON pemeriksaan.kode_periksa=pembayaran.kode_periksa "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter "
                    + "WHERE id='"+id+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtkodepembayaran.setText(res.getString(1));
                txtkodeperiksa.setText(res.getString(2));
                txtnamapasien.setText(res.getString(13));
                txtnamadokter.setText(res.getString(19));
                txttindakan.setText(res.getString(11));
                txttotal.setText(res.getString(3));
                txtbayar.setText(res.getString(4));
                txtkembalian.setText(res.getString(5));
                
                
                
                btnsimpan.setEnabled(false);
                btnupdate.setEnabled(true);
                btndelete.setEnabled(true);
                btncaripemeriksaan.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
        
        
    }//GEN-LAST:event_btncariActionPerformed

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        if(txtbayar.getText().equals("") || txtbayar.getText().equals("0")){
           JOptionPane.showMessageDialog(rootPane, "Nominal Bayar Tidak Boleh Kosong!!!"); 
           txtbayar.setText(txttotal.getText());
        }else {
            int harga = Integer.parseInt(txttotal.getText());
            int bayar = Integer.parseInt(txtbayar.getText());
            int kembalian = bayar - harga;
            txtkembalian.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_txtbayarKeyReleased

    private void btncaripemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripemeriksaanActionPerformed
        String kode = JOptionPane.showInputDialog(null, "Cari Berdasarkan Kode Pemeriksaan!!!");
        try{
            String sql = "SELECT * FROM pemeriksaan "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter "
                    + "WHERE kode_periksa='"+kode+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtkodeperiksa.setText(res.getString(1));
                txtnamapasien.setText(res.getString(8));
                txtnamadokter.setText(res.getString(14));
                txttindakan.setText(res.getString(6));
                
                rawat = res.getString(6);
                kodeperiksa = res.getString(1);
                
                if(rawat.equals("Rawat Jalan")){
                    try{
                        String sqlr = "SELECT * FROM rawat_jalan "
                                + "WHERE kode_periksa='"+kodeperiksa+"'";
                        java.sql.Connection connr=(Connection)Koneksi.configDB();
                        java.sql.Statement stmr = connr.createStatement();
                        java.sql.ResultSet resr = stmr.executeQuery(sqlr);

                        if(resr.next()){
                            txttotal.setText(resr.getString(5));
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                            reset();
                        }
                    } catch (Exception e){
                        System.out.print(e);
                        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                    } 
                
                }else if(rawat.equals("Rawat Inap")){
                    try{
                        String sqlr = "SELECT * FROM rawat_inap "
                                + "WHERE kode_periksa='"+kodeperiksa+"'";
                        java.sql.Connection connr=(Connection)Koneksi.configDB();
                        java.sql.Statement stmr = connr.createStatement();
                        java.sql.ResultSet resr = stmr.executeQuery(sqlr);

                        if(resr.next()){
                            txttotal.setText(resr.getString(6));
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                            reset();
                        }
                    } catch (Exception e){
                        System.out.print(e);
                        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                    } 
                
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_btncaripemeriksaanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(txtkodepembayaran.getText().equals("") || txtkodeperiksa.getText().equals("") || txtnamapasien.getText().equals("") || txtnamadokter.getText().equals("") || txttindakan.getText().equals("") || txtbayar.getText().equals("") || txttotal.getText().equals("") || txtkembalian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Form Tidak Boleh Ada Yang Kosong!!!");
        }else{
            try {
                String sql = "INSERT INTO pembayaran(id, kode_periksa, harga, pembayaran, kembalian) "
                    + "VALUES('"+txtkodepembayaran.getText()+"', '"+txtkodeperiksa.getText()+"', '"+txttotal.getText()+"', '"+txtbayar.getText()+"', '"+txtkembalian.getText()+"')";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Prosess Simpan Data Pembayaran Berhasil..");
                reset();
                kodeBayar();

            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            String sql = "UPDATE pembayaran SET kode_periksa='"+txtkodeperiksa.getText()+"', harga='"+txttotal.getText()+"', pembayaran='"+txtbayar.getText()+"', kembalian='"+txtkembalian.getText()+"' WHERE id = '"+txtkodepembayaran.getText()+"'";
            java.sql.Connection conn = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Pembayaran Berhasil...");
            kodeBayar();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        reset();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int tanya = JOptionPane.showConfirmDialog(null, "Yakin untuk menghapus data ini?","Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(tanya==0){
            try{
                String sql = "DELETE FROM pembayaran WHERE id='"+txtkodepembayaran.getText()+"'";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Hapus Data Rawat Jalan Berhasil....");
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            reset();
            kodeBayar();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnDataPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPembayaranActionPerformed
        DataPembayaranForm dataPembayaran = new DataPembayaranForm();
        this.getDesktopPane().add(dataPembayaran);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = dataPembayaran.getSize();

        dataPembayaran.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);
        
        dataPembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDataPembayaranActionPerformed

    private void btncetakfakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakfakturActionPerformed
        CetakBuktiPembayaran buktiPembayaran = new CetakBuktiPembayaran();
        buktiPembayaran.setVisible(true);
        String kodePembayaran = txtkodepembayaran.getText();
        buktiPembayaran.Cetak(kodePembayaran);
    }//GEN-LAST:event_btncetakfakturActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataPembayaran;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncaripemeriksaan;
    private javax.swing.JButton btncetakfaktur;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel panelFormPembayaran;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtkodepembayaran;
    private javax.swing.JTextField txtkodeperiksa;
    private javax.swing.JTextField txtnamadokter;
    private javax.swing.JTextField txtnamapasien;
    private javax.swing.JTextField txttindakan;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
