/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import main.pemeriksaan.PemeriksaanForm;
import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Locale;
import main.dokter.DataDokterForm;
import main.kamar.DataKamarForm;
import main.obat.DataObatForm;
import main.pasien.DataPasienForm;
import main.pembayaran.PembayaranForm;
import main.rawat.rawatinap.RawatInapForm;
import main.rawat.rawatjalan.RawatJalanForm;
import main.spesialis.DataSpesialisForm;

/**
 *
 * @author User
 */
public class MainForm extends javax.swing.JFrame {

    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String tanggal = smpdtfmt.format(tglsekarang);
    
    public MainForm() {
        initComponents();
        txttanggal.setText(tanggal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        gDashboard = new javax.swing.JLabel();
        btnPemeriksaan = new javax.swing.JButton();
        gPemeriksaan = new javax.swing.JLabel();
        btnPembayaran = new javax.swing.JButton();
        gPembayaran = new javax.swing.JLabel();
        gPasien = new javax.swing.JLabel();
        btnPasien = new javax.swing.JButton();
        gDokter = new javax.swing.JLabel();
        btnDokter = new javax.swing.JButton();
        btnSpesialis = new javax.swing.JButton();
        gSpesialis = new javax.swing.JLabel();
        btnObat = new javax.swing.JButton();
        gObat = new javax.swing.JLabel();
        btnKamar = new javax.swing.JButton();
        gKamar = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnRawatInap = new javax.swing.JButton();
        gRawatInap = new javax.swing.JLabel();
        btnRawatJalan = new javax.swing.JButton();
        gRawatJalan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        txtcari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(780, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        panelSidebar.setRequestFocusEnabled(false);

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(115, 87, 243));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/window-outline.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setAutoscrolls(true);
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setDefaultCapable(false);
        btnDashboard.setDisplayedMnemonicIndex(0);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setFocusable(false);
        btnDashboard.setIconTextGap(9);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        gDashboard.setBackground(new java.awt.Color(102, 102, 255));
        gDashboard.setOpaque(true);

        btnPemeriksaan.setBackground(new java.awt.Color(255, 255, 255));
        btnPemeriksaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPemeriksaan.setForeground(new java.awt.Color(115, 87, 243));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clipboard-square-symbol.png"))); // NOI18N
        btnPemeriksaan.setText("Pemeriksaan");
        btnPemeriksaan.setAutoscrolls(true);
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setBorderPainted(false);
        btnPemeriksaan.setContentAreaFilled(false);
        btnPemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPemeriksaan.setDefaultCapable(false);
        btnPemeriksaan.setFocusPainted(false);
        btnPemeriksaan.setFocusable(false);
        btnPemeriksaan.setIconTextGap(9);
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });

        gPemeriksaan.setBackground(new java.awt.Color(255, 255, 255));
        gPemeriksaan.setOpaque(true);

        btnPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        btnPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPembayaran.setForeground(new java.awt.Color(115, 87, 243));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/window-outline.png"))); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.setAutoscrolls(true);
        btnPembayaran.setBorder(null);
        btnPembayaran.setBorderPainted(false);
        btnPembayaran.setContentAreaFilled(false);
        btnPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPembayaran.setDefaultCapable(false);
        btnPembayaran.setFocusPainted(false);
        btnPembayaran.setFocusable(false);
        btnPembayaran.setIconTextGap(9);
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        gPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        gPembayaran.setOpaque(true);

        gPasien.setBackground(new java.awt.Color(255, 255, 255));
        gPasien.setOpaque(true);

        btnPasien.setBackground(new java.awt.Color(255, 255, 255));
        btnPasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPasien.setForeground(new java.awt.Color(115, 87, 243));
        btnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2791.png"))); // NOI18N
        btnPasien.setText("Pasien");
        btnPasien.setAutoscrolls(true);
        btnPasien.setBorder(null);
        btnPasien.setBorderPainted(false);
        btnPasien.setContentAreaFilled(false);
        btnPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasien.setDefaultCapable(false);
        btnPasien.setFocusPainted(false);
        btnPasien.setFocusable(false);
        btnPasien.setIconTextGap(9);
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });

        gDokter.setBackground(new java.awt.Color(255, 255, 255));
        gDokter.setOpaque(true);

        btnDokter.setBackground(new java.awt.Color(255, 255, 255));
        btnDokter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDokter.setForeground(new java.awt.Color(115, 87, 243));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2790.png"))); // NOI18N
        btnDokter.setText("Dokter");
        btnDokter.setAutoscrolls(true);
        btnDokter.setBorder(null);
        btnDokter.setBorderPainted(false);
        btnDokter.setContentAreaFilled(false);
        btnDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDokter.setDefaultCapable(false);
        btnDokter.setFocusPainted(false);
        btnDokter.setFocusable(false);
        btnDokter.setIconTextGap(9);
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });

        btnSpesialis.setBackground(new java.awt.Color(255, 255, 255));
        btnSpesialis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSpesialis.setForeground(new java.awt.Color(115, 87, 243));
        btnSpesialis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/window-outline.png"))); // NOI18N
        btnSpesialis.setText("Spesialis");
        btnSpesialis.setAutoscrolls(true);
        btnSpesialis.setBorder(null);
        btnSpesialis.setBorderPainted(false);
        btnSpesialis.setContentAreaFilled(false);
        btnSpesialis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpesialis.setDefaultCapable(false);
        btnSpesialis.setFocusPainted(false);
        btnSpesialis.setFocusable(false);
        btnSpesialis.setIconTextGap(9);
        btnSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpesialisActionPerformed(evt);
            }
        });

        gSpesialis.setBackground(new java.awt.Color(255, 255, 255));
        gSpesialis.setOpaque(true);

        btnObat.setBackground(new java.awt.Color(255, 255, 255));
        btnObat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnObat.setForeground(new java.awt.Color(115, 87, 243));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/window-outline.png"))); // NOI18N
        btnObat.setText("Obat");
        btnObat.setAutoscrolls(true);
        btnObat.setBorder(null);
        btnObat.setBorderPainted(false);
        btnObat.setContentAreaFilled(false);
        btnObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObat.setDefaultCapable(false);
        btnObat.setFocusPainted(false);
        btnObat.setFocusable(false);
        btnObat.setIconTextGap(9);
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });

        gObat.setBackground(new java.awt.Color(255, 255, 255));
        gObat.setOpaque(true);

        btnKamar.setBackground(new java.awt.Color(255, 255, 255));
        btnKamar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKamar.setForeground(new java.awt.Color(115, 87, 243));
        btnKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/window-outline.png"))); // NOI18N
        btnKamar.setText("Kamar");
        btnKamar.setAutoscrolls(true);
        btnKamar.setBorder(null);
        btnKamar.setBorderPainted(false);
        btnKamar.setContentAreaFilled(false);
        btnKamar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKamar.setDefaultCapable(false);
        btnKamar.setFocusPainted(false);
        btnKamar.setFocusable(false);
        btnKamar.setIconTextGap(9);
        btnKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKamarActionPerformed(evt);
            }
        });

        gKamar.setBackground(new java.awt.Color(255, 255, 255));
        gKamar.setOpaque(true);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        btnRawatInap.setBackground(new java.awt.Color(255, 255, 255));
        btnRawatInap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRawatInap.setForeground(new java.awt.Color(115, 87, 243));
        btnRawatInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clipboard-square-symbol.png"))); // NOI18N
        btnRawatInap.setText("Rawat Inap");
        btnRawatInap.setAutoscrolls(true);
        btnRawatInap.setBorder(null);
        btnRawatInap.setBorderPainted(false);
        btnRawatInap.setContentAreaFilled(false);
        btnRawatInap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRawatInap.setDefaultCapable(false);
        btnRawatInap.setFocusPainted(false);
        btnRawatInap.setFocusable(false);
        btnRawatInap.setIconTextGap(9);
        btnRawatInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRawatInapActionPerformed(evt);
            }
        });

        gRawatInap.setBackground(new java.awt.Color(255, 255, 255));
        gRawatInap.setOpaque(true);

        btnRawatJalan.setBackground(new java.awt.Color(255, 255, 255));
        btnRawatJalan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRawatJalan.setForeground(new java.awt.Color(115, 87, 243));
        btnRawatJalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clipboard-square-symbol.png"))); // NOI18N
        btnRawatJalan.setText("Rawat Jalan");
        btnRawatJalan.setAutoscrolls(true);
        btnRawatJalan.setBorder(null);
        btnRawatJalan.setBorderPainted(false);
        btnRawatJalan.setContentAreaFilled(false);
        btnRawatJalan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRawatJalan.setDefaultCapable(false);
        btnRawatJalan.setFocusPainted(false);
        btnRawatJalan.setFocusable(false);
        btnRawatJalan.setIconTextGap(9);
        btnRawatJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRawatJalanActionPerformed(evt);
            }
        });

        gRawatJalan.setBackground(new java.awt.Color(255, 255, 255));
        gRawatJalan.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("SMKN 9");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnPembayaran))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnPasien))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnDokter))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnSpesialis))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gObat, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnObat))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnKamar))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gRawatJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnRawatJalan)))
                    .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnPemeriksaan))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gRawatInap, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnRawatInap))
                        .addGroup(panelSidebarLayout.createSequentialGroup()
                            .addComponent(gDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logo)
                                .addComponent(btnDashboard)))))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gPemeriksaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gRawatInap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRawatInap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gRawatJalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRawatJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gSpesialis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 550));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(null);

        txtcari.setBackground(new java.awt.Color(240, 240, 240));
        txtcari.setForeground(new java.awt.Color(204, 204, 204));
        txtcari.setText("Cari");
        txtcari.setBorder(null);
        panelHeader.add(txtcari);
        txtcari.setBounds(50, 20, 150, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2794.png"))); // NOI18N
        panelHeader.add(jLabel4);
        jLabel4.setBounds(470, 10, 40, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2796.png"))); // NOI18N
        panelHeader.add(jLabel2);
        jLabel2.setBounds(10, 0, 200, 60);

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        panelHeader.add(btnlogout);
        btnlogout.setBounds(670, 20, 40, 30);

        jLabel3.setFont(new java.awt.Font("Poppins ExtraLight", 0, 12)); // NOI18N
        jLabel3.setText("Irfan Nuha");
        panelHeader.add(jLabel3);
        jLabel3.setBounds(510, 20, 140, 30);

        txttanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttanggal.setText("tanggal");
        panelHeader.add(txttanggal);
        txttanggal.setBounds(240, 20, 80, 20);

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 780, 70));

        DesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        DesktopPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        DesktopPane.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 780, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(102, 102, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        PemeriksaanForm pemeriksaan = new PemeriksaanForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = pemeriksaan.getSize();

        pemeriksaan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pemeriksaan.setVisible(true);

        //add panel
        DesktopPane.add(pemeriksaan);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        gDashboard.setBackground(new Color(102, 102, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        DashboardForm dashboard = new DashboardForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dashboard.getSize();

        dashboard.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dashboard.setVisible(true);

        //add panel
        DesktopPane.add(dashboard);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(102, 102, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        DataDokterForm dataDokter = new DataDokterForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataDokter.getSize();

        dataDokter.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataDokter.setVisible(true);

        //add panel
        DesktopPane.add(dataDokter);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpesialisActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(102, 102, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        DataSpesialisForm dataSpesialis = new DataSpesialisForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataSpesialis.getSize();

        dataSpesialis.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataSpesialis.setVisible(true);

        //add panel
        DesktopPane.add(dataSpesialis);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnSpesialisActionPerformed

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(102, 102, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        DataKamarForm dataKamar = new DataKamarForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataKamar.getSize();

        dataKamar.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataKamar.setVisible(true);

        //add panel
        DesktopPane.add(dataKamar);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnKamarActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(102, 102, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        DataObatForm dataObat = new DataObatForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataObat.getSize();

        dataObat.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataObat.setVisible(true);

        //add panel
        DesktopPane.add(dataObat);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(102, 102, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        DataPasienForm dataPasien = new DataPasienForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataPasien.getSize();

        dataPasien.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataPasien.setVisible(true);

        //add panel
        DesktopPane.add(dataPasien);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnPasienActionPerformed

    private void btnRawatInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRawatInapActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(102, 102, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        RawatInapForm rawatInap = new RawatInapForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = rawatInap.getSize();

        rawatInap.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        rawatInap.setVisible(true);

        //add panel
        DesktopPane.add(rawatInap);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnRawatInapActionPerformed

    private void btnRawatJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRawatJalanActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(255, 255, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(102, 102, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        RawatJalanForm rawatJalan = new RawatJalanForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = rawatJalan.getSize();

        rawatJalan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        rawatJalan.setVisible(true);

        //add panel
        DesktopPane.add(rawatJalan);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnRawatJalanActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        gDashboard.setBackground(new Color(255, 255, 255));
        gDokter.setBackground(new Color(255, 255, 255));
        gPasien.setBackground(new Color(255, 255, 255));
        gPemeriksaan.setBackground(new Color(255, 255, 255));
        gPembayaran.setBackground(new Color(102, 102, 255));
        gSpesialis.setBackground(new Color(255, 255, 255));
        gObat.setBackground(new Color(255, 255, 255));
        gKamar.setBackground(new Color(255, 255, 255));
        gRawatInap.setBackground(new Color(255, 255, 255));
        gRawatJalan.setBackground(new Color(255, 255, 255));

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        PembayaranForm pembayaran = new PembayaranForm();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = pembayaran.getSize();

        pembayaran.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pembayaran.setVisible(true);

        //add panel
        DesktopPane.add(pembayaran);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JDesktopPane DesktopPane = new javax.swing.JDesktopPane();
    public javax.swing.JButton btnDashboard;
    public javax.swing.JButton btnDokter;
    public javax.swing.JButton btnKamar;
    public javax.swing.JButton btnObat;
    public javax.swing.JButton btnPasien;
    public javax.swing.JButton btnPembayaran;
    public javax.swing.JButton btnPemeriksaan;
    public javax.swing.JButton btnRawatInap;
    public javax.swing.JButton btnRawatJalan;
    public javax.swing.JButton btnSpesialis;
    private javax.swing.JLabel btnlogout;
    public javax.swing.JLabel gDashboard;
    public javax.swing.JLabel gDokter;
    public javax.swing.JLabel gKamar;
    public javax.swing.JLabel gObat;
    public javax.swing.JLabel gPasien;
    public javax.swing.JLabel gPembayaran;
    public javax.swing.JLabel gPemeriksaan;
    public javax.swing.JLabel gRawatInap;
    public javax.swing.JLabel gRawatJalan;
    public javax.swing.JLabel gSpesialis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JTextField txtcari;
    private javax.swing.JLabel txttanggal;
    // End of variables declaration//GEN-END:variables
}
