/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.spesialis;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import main.Koneksi;
import main.cetak.CetakDataSpesialis;

/**
 *
 * @author User
 */
public class DataSpesialisForm extends javax.swing.JInternalFrame {

    private void tampilkan_data(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblspesialis.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM spesialis";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(2)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public DataSpesialisForm() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataSpesialis = new javax.swing.JPanel();
        jScrollPane50 = new javax.swing.JScrollPane();
        tblspesialis = new javax.swing.JTable();
        jLabel81 = new javax.swing.JLabel();
        jButton37 = new javax.swing.JButton();
        btnFormSpesialis = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(780, 480));

        panelDataSpesialis.setBackground(new java.awt.Color(255, 255, 255));
        panelDataSpesialis.setPreferredSize(new java.awt.Dimension(780, 480));

        jScrollPane50.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblspesialis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Spesialis", "Nama Spesialis"
            }
        ));
        tblspesialis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane50.setViewportView(tblspesialis);

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(102, 102, 255));
        jLabel81.setText("Data Spesialis");

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group.png"))); // NOI18N
        jButton37.setText(" Print");
        jButton37.setFocusable(false);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        btnFormSpesialis.setText("Kelola Data");
        btnFormSpesialis.setFocusable(false);
        btnFormSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSpesialisActionPerformed(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2803.png"))); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataSpesialisLayout = new javax.swing.GroupLayout(panelDataSpesialis);
        panelDataSpesialis.setLayout(panelDataSpesialisLayout);
        panelDataSpesialisLayout.setHorizontalGroup(
            panelDataSpesialisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataSpesialisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrefresh)
                .addGap(18, 18, 18)
                .addComponent(btnFormSpesialis)
                .addGap(18, 18, 18)
                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(panelDataSpesialisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDataSpesialisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel81))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelDataSpesialisLayout.setVerticalGroup(
            panelDataSpesialisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataSpesialisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDataSpesialisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFormSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDataSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDataSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSpesialisActionPerformed
        SpesialisForm spesialis = new SpesialisForm();
        this.getDesktopPane().add(spesialis);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = spesialis.getSize();

        spesialis.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);
        
        spesialis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFormSpesialisActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkan_data();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        CetakDataSpesialis dataSpesialis = new CetakDataSpesialis();
        dataSpesialis.setVisible(true);
    }//GEN-LAST:event_jButton37ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormSpesialis;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton37;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JPanel panelDataSpesialis;
    private javax.swing.JTable tblspesialis;
    // End of variables declaration//GEN-END:variables
}
