/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.pemeriksaan;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.Koneksi;
import main.cetak.CetakDataPemeriksaan;

/**
 *
 * @author User
 */
public class DataPemeriksaanForm extends javax.swing.JInternalFrame {

    
    private void tampilkanData(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblpemeriksaan.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pemeriksaan "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(8),res.getString(14),res.getString(4),res.getString(5), res.getString(6)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public DataPemeriksaanForm() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataPemeriksaan = new javax.swing.JPanel();
        jScrollPane47 = new javax.swing.JScrollPane();
        tblpemeriksaan = new javax.swing.JTable();
        jLabel77 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        btnformpemeriksaan = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(780, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDataPemeriksaan.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane47.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblpemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pemeriksaan", "Nama Pasien", "Nama Dokter", "Diagnosa", "Tanggal Periksa", "Tindakan"
            }
        ));
        tblpemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane47.setViewportView(tblpemeriksaan);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(102, 102, 255));
        jLabel77.setText("Data Pemeriksaan");

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group.png"))); // NOI18N
        jButton21.setText(" Print");
        jButton21.setFocusable(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        btnformpemeriksaan.setText("Kelola Data Pemeriksaan");
        btnformpemeriksaan.setFocusable(false);
        btnformpemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformpemeriksaanActionPerformed(evt);
            }
        });

        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group 2803.png"))); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataPemeriksaanLayout = new javax.swing.GroupLayout(panelDataPemeriksaan);
        panelDataPemeriksaan.setLayout(panelDataPemeriksaanLayout);
        panelDataPemeriksaanLayout.setHorizontalGroup(
            panelDataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataPemeriksaanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnformpemeriksaan)
                .addGap(18, 18, 18)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(panelDataPemeriksaanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel77))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelDataPemeriksaanLayout.setVerticalGroup(
            panelDataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataPemeriksaanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnformpemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(panelDataPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkanData();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnformpemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformpemeriksaanActionPerformed
        PemeriksaanForm pemeriksaan = new PemeriksaanForm();
        this.getDesktopPane().add(pemeriksaan);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = pemeriksaan.getSize();

        pemeriksaan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);
        
        pemeriksaan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnformpemeriksaanActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        CetakDataPemeriksaan dataPemeriksaan = new CetakDataPemeriksaan();
        dataPemeriksaan.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnformpemeriksaan;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JPanel panelDataPemeriksaan;
    private javax.swing.JTable tblpemeriksaan;
    // End of variables declaration//GEN-END:variables
}
